### ISSUE TITLE
Add support for vertical text

### ISSUE THREAD

**Issue by raichu** [fabricjs/fabric.js#511]
Vertical text is very commonly used with CJK text, so please please :)
##

**Comment by RottenFinger** [comment]
@raichu did you make it?

**Comment by limichange** [comment]
😅 what's the result?

**Comment by bkstorm** [comment]
I think this feature is necessary. Actually, I'm trying to implement vertical text.

**Comment by asturur** [comment]
Please before actually implementing it with the idea that the feature is outside the of your personal project, open an issue on the api-discussion repository and let s discuss there:
what languages use vertical text and what it looks like.
how vertical text static should work.
how interaction should work.
what code is necessary.


i ll be very happy to be available in prototyping and help, so that we can actually do something that can be merged and mantained.

**Comment by OPY-bbt** [comment]
Is there any progress on this？

**Comment by TsuchiyaMasahiro** [comment]
In Japanese, vertical writing starts at the top right and goes down, and when there is a line break, it moves one line to the left. 
I found someone's program as follows.

      var vertical_text = function(context, text, x, y) {
            var textList = text.split('\n');
            var lineHeight = context.measureText("あ").width;
           
           textList.forEach(function(elm, i) {
                Array.prototype.forEach.call(elm, function(ch, j) {
                    context.fillText(ch, x-lineHeight*i, y+lineHeight*j);
                });
           });
      };

I hope that fabric.js will support vertical  text, too.

**Comment by asturur** [comment]
i would very much support it.

How the cursor is supposed to work? is it vertical near the last character or is horizontal between chars?

Also do lineheight make sense, and any kind of alignment does?

**Comment by wildccy** [comment]
> 我会非常支持。
> 
> 游标应该如何工作？是在最后一个字符附近垂直还是在字符之间水平？
> 
> lineheight是否也有意义，并且任何对齐方式都可以吗？

It should be at the inter-character level at least in Chinese and Japanese. I think it's really time to add this feature because you can't just rely on /n
And happy Christmas Eve！

**Comment by asturur** [comment]
So the character should be HORIZONTAL between chars. Do you have a screenshot of any vertical text writing app to see it in action?

How does MS word or google docs behave with vertical text?

What do people use for writing vertically that can we look at?

**Comment by TsuchiyaMasahiro** [comment]
MS word (Japanese)
![japanese2](https://user-images.githubusercontent.com/22161480/71537074-3c149a00-295a-11ea-8087-265bf8751aca.gif)

**Comment by TsuchiyaMasahiro** [comment]
MS word textbox version
![japanese1](https://user-images.githubusercontent.com/22161480/71537091-5c445900-295a-11ea-8835-e2f16f8c5f5b.gif)

**Comment by TsuchiyaMasahiro** [comment]
![japanese_position](https://user-images.githubusercontent.com/22161480/71537184-b0037200-295b-11ea-9d7c-2412943139b2.png)

**Comment by asturur** [comment]
Why some character are smaller? Is there some rule or because are used as grapheme clusters?
I would not add specific language information that requires knowledge of that specific language.

**Comment by TsuchiyaMasahiro** [comment]
Some Japanese characters are smaller.
For example, UnicodeU+3041, 3043, 3045, etc. are smaller than others.
It is Japanese language rule.

OK, if you would support the cursor orientation and movement for vertical writing, maybe I can customize it by myself.

**Comment by asturur** [comment]
does actual standard canvas text make those character smaller? or is an ignored rule so far? I m talking by canvas in general not fabric in particular.

I would love to start this. I have some info now.

**Comment by TsuchiyaMasahiro** [comment]
Yes, those characters are made smaller in an actual standard canvas.

For example below, a character [ゆ] is smaller than others. 
[https://jsfiddle.net/uemon/wpL3m4au/](https://jsfiddle.net/uemon/wpL3m4au/)

In English, lowercase letters are smaller than uppercase letters.
In the same way, some Japanese letters are smaller than other.

Those letters are set in an upper right position in vertical text, as I mentioned yesterday.

**Comment by asturur** [comment]
ok an in vertical alignment it goes top right.
That make sense.

We could say that vertical text is like if we rotate a normal textbox clockwise of 90 degree
but then we rotate each character counter clockwise 90 degree

**Comment by TsuchiyaMasahiro** [comment]
Some Japanese symbol characters (such as '[', '<','-') rotate clockwise of 90 degree, and it is not rotated counter clockwise 90 degree in vertical text.

When you rotate each character coutner clockwise 90 degree, could you add exception as below ?

-----
fabric.Object.prototype.exceptionVerticalRoratin = ['[, ']', '<','>'];  <-★each user can define it accroding to their own language.

if ( each character of vertical text is in the exceptionVerticalRoratin array ) {
	don't rotate counter clockwise 90 degree
} else {
	rotate counter clockwise 90 degree
}

**Comment by asturur** [comment]
so the brackets are laid down horizontally, following the text flow, and so taking less space? do they break the caracteristic block sizing of japanese writing? or do they get extra space?

**Comment by TsuchiyaMasahiro** [comment]
I think they take the same space and don't break the character block size of Japanese writing.

It may depend on the kind of the font.
In a case of fixed-width font, those symbol characters take the same space.
And in a case of proportional font, those symbol characters take less space.

![compare](https://user-images.githubusercontent.com/22161480/71638252-a69d4100-2c9e-11ea-981f-355181d42dd4.png)

**Comment by canhnht** [comment]
Hi everyone. Thanks for raising the feature vertical writing.
I would like to contribute to implement this feature. This is very popular in CJK text.
Is there any progress on this feature?

**Comment by canhnht** [comment]
I'm exploring text.class.js in fabricjs's source code to see how to add vertical writing.
I'm thinking of implementing inputting vertical text in textbox.
In canvas's Web API, I don't find any API that supports typing text in a textbox. But fabricjs can support that.
How can fabricjs support typing text in a textbox inside canvas?

**Comment by asturur** [comment]
Hi @canhnht fabricJS can type on a canvas because it use an hidden textarea which content then gets processed by the code and painted on the canvas.

It would be good to have vertical text and also vertical text knowledge, because the main factor is that i have no idea how vertical text work and what users would expect from it ( is it RTL or LTR, how do line break works and so on ).

You could start looking at how text rendering works and how you would reposition text each grapheme cluster one under the other. The real writing would still happen on a classic horizontal textarea, that is invisible.

**Comment by canhnht** [comment]
Oh, I got it. Thanks for your clarification.
So I think the mechanism is quite similar to examples in this gist https://gist.github.com/aya-eiya/1721182
I will try implementing vertical writing based on that.
Is the main code for text rendering and repositioning grapheme in the file itext.class.js? Would you mind to explain a little bit about working flow of rendering text?
Thanks in advance.

**Comment by asturur** [comment]
yes i can explain everything and support you in delivering the feature if you have the will and time to do so.
You find most of the code in text.class.js, you should given my experience my suggestion for possible steps are:

1) forgetting the interactive part and the cursor, just take a normal text object, write something on it, and work to have it measured and displayed vertically.
... once that work and is merged ( because we will test and merge code in small portions )

2) look at iText class, look at cursor rendering and position work ( how it gets moved with keyboard and so on, text selection for text ranges ) and adapt the cursor and selection to vertical text.
... once that work and is merged ....

3) we can look at Textbox and see if the flow adjustment make sense with vertical text too.

Does this make sense to you?

Small incremental code changes is the key to get things done, because fabricjs is large and is hard to understand and keep everything under control with large changes.

**Comment by canhnht** [comment]
Thanks a lot for your suggestion. 👍 
Fabricjs is really huge. 😅  I will try to add incremental code changes and merge small code changes as soon as possible.

I have explored fabric's source code and understood more about components in Text, IText and Textbox classes.
I made some changes in fabric's code and built a demo https://github.com/canhnht/FabricJS-Demo.
In this demo, it can show that these things are feasible:
- Cursor can be rendered as horizontal bar.
- Text can be displayed and appended vertically when user inputs.
- Text selection can be rendered vertically.
But the positions of cursor, text and selection region are not correct yet.
I'm excited to keep implementing vertical writing.
From my understanding, to implement vertical writing, I will need to change these things in fabric's code:
- Cursor.
- Text selection.
- Position of character.
- Position of hidden textarea.
- Boundary box of text.
- Support for special characters: "{}()[]「」『』（）【】［］｛｝…─━ー=＝～｜|". You can see example in this site http://vertically.works/
- Text alignment: left, right, center.
- Vertical fonts (I just heard about it and not clear yet about affect of vertical fonts.)

From your suggestion, I will start from step 1.
It seems that this step is related to calculation of width and height of character, boundary box and many other things.
Currently I'm also stuck in this part. Could you help to point out the code for calculating these things when a text object is initialized?
Thanks in advance.

**Comment by asturur** [comment]
As soon as i am back to a computer i ll link relevant pieces of code.

Fabricjs does nor measure height, it assumes is in relation with fontSize, while this can be wrong for vertical text, i m fine starting keeping that assumption.

A minimal piece of work could totally be also just add a 'vertical' true/false property to text and just let the code that calculate text width/height return the correct size.

Following with a proper rendering PR.

For the special characters i would not do anything, who uses vertical text knows how to handle them i presume, and how to input them too.

i ll write asap.

**Comment by asturur** [comment]
You have to give a look at initDimensions and go deep to the calls up to:

https://github.com/fabricjs/fabric.js/blob/master/src/shapes/text.class.js#L712

`_measureLine` is the building block of `measureLine` that is of `getLineWidth` up to `getTextWidth`.

It run over the characters one by one and with `getGraphemeBox` https://github.com/fabricjs/fabric.js/blob/master/src/shapes/text.class.js#L744 will measure every char taking in account kerning.

Now getGraphemeBox could be as good as it is., with the difference that if the text is vertical oriente:

textHeight is the lenght of the longest line measured as if each char was typed one under the other
textWidth is the sum of the largest char width for each column of text.

There are some concept like lineHeigh that would become the space between each column and also charSpacing that would still be the distance between each char inside the same column.

**Comment by canhnht** [comment]
Thanks a lot for explaining relevant code and all the concepts. <3
I also added a 'vertical' true/false property to IText and added another version for each function that is affected by vertical writing.
I should change it to Text, since it's the base class of text object and will be inherited by IText and Textbox.

About kerned width, it seems to be the space between characters in a text. In vertical writing, will its calculation need to be changed?

**Comment by asturur** [comment]
i think we do not have the tools for kernedwidth vertically. Unless canvas support it natively.

for now vertical text will have all the chars high the same, no kerning, and that's it.

For me is important to have vertical text ( like also right to left ) because is not about an extra feature but a feature that is culturally important. So the first draft won't be perfect but will be there, and see it working will make possible for more people to improve it.

**Comment by canhnht** [comment]
Hi @asturur, I'm quite confused about mechanism of positioning and resizing of boundary box in text object.
In normal writing (i.e. horizontal text), when text is changed:
- Position of top left corner does not move.
- The boundary box will be expanded to the right and to bottom.
In vertical writing, when text is changed:
- Position of top right corner does not move.
- The boundary box will be expanded to the left and to bottom.

The resizing and positioning of boundary box in vertical writing is quite different from normal writing.
I don't know where to change that mechanism.
Could you help to point out part of the code for calculating boundary box?
Thanks in advance.

**Comment by asturur** [comment]
You shouldn't be worrying of those things already :)
Anyway that is not a fabricJS coded behaviour related to text.
That is a side effect of the default object origin being top/left based.

If you set originX = 'center' and originY = 'center' for your object you will see that for normal text, the bounding box expands on both sizes , horizontally and vertically.

I know that vertical text are generally moving from the right to the left, but please ignore that and let's look into it when a single vertical text line works.

If you want to open a PR you should be better contributing small incremental changes toward the final goal or i won't be able to review and merge them.

**Comment by canhnht** [comment]
Thanks a lot for your explanation.
I'm trying to understand how other functions and classes of text object interact with each other and the calculations of some properties in text class.
I will try to get a vertical text line work first.

**Comment by asturur** [comment]
Ideally Text does everything, and IText handles interactivity. Still ideally Textbox will disappear and wrapping will be an option in the Text basic class, as well as rtl and vertical.

**Comment by manhthepixta** [comment]
Hi any update on this?

**Comment by asturur** [comment]
no.
I have 5-7 small fixes i want to get out and then work on rtl text and then vertical text

**Comment by Saberjsd** [comment]
Hi again!
I have met an advanced demand too.(〃'▽'〃)
emmmmm..........

**Comment by Saberjsd** [comment]
like css  `writing-mode: vertical-lr;`

**Comment by Saberjsd** [comment]
like css `writing-mode: vertical-rl;`

**Comment by manhthepixta** [comment]
@asturur This gist might help. From a Japanese person.
https://gist.github.com/aya-eiya/1721182
Japanese character displays very well.

**Comment by zhuziqingdemao** [comment]
> no.
> I have 5-7 small fixes i want to get out and then work on rtl text and then vertical text

Hi ! Has the problem been solved? I need the ability to arrange multiple lines of text vertically 😭

**Comment by asturur** [comment]
No @zhuziqingdemao no one worked on it yet.

**Comment by thuytv-scuti** [comment]
@asturur I've wrote a sample, it's a mess but it worked for me, hope it help.
it will be great if you guys help me optimize it.
https://gist.github.com/thuytv-scuti/2848ebd6214a670e6d87ddfce388448b

**Comment by asturur** [comment]
hey @thuytv-scuti thank you! i ll check as soon as possible.
I m coming back after a pause and have a backlog to clear

**Comment by thuytv-scuti** [comment]
@asturur I have created a repo for it
https://github.com/thuytv-scuti/fabric-CJK-vertical

**Comment by asturur** [comment]
thanks. If there is useful code to make vertical text work, what is your preference to integrate it?

**Comment by thuytv-scuti** [comment]
> thanks. If there is useful code to make vertical text work, what is your preference to integrate it?

What do you mean of preference, I am using your work free of charge, that's my preference if it ok.

**Comment by asturur** [comment]
Sure i mean, if that code brings to working vertical text ( i did not look at it yet ) do you want to open a PR by yourself to have the work recognized on a commit? How can we eventually recognize your work.

**Comment by asturur** [comment]
i don't think is agnostic. It could be, but probably it isn't.
I think it depends from which Math library the javascript engine links in.
You can have tests failing in node and not in browser or failing in firefox and not in chrome, even just with matrices code.
At leat it happened to me and that is why some tests have the `toFixed()` hack

**Comment by thuytv-scuti** [comment]
> Sure i mean, if that code brings to working vertical text ( i did not look at it yet ) do you want to open a PR by yourself to have the work recognized on a commit? How can we eventually recognize your work.

Oh yeah, I sure want my work to be recognize, I will open a PR by myself ^^.
But my current code comes in difference convention compare to fabric core, so I will need sometime to convert it to proper convention.

**Comment by carior** [comment]
> @asturur I have created a repo for it https://github.com/thuytv-scuti/fabric-CJK-vertical

When displayed vertically, stretching deforms the text

**Comment by thuytv-gl** [comment]
Hi @carior, I was busy for few months and not working on this feature at all.  
I am started working on the vertical text support on this github account, will open a PR asap!

**Comment by ruojianll** [comment]
This feature is inneed.

**Comment by xiaowangsmile** [comment]
This feature is inneed.

**Comment by thuytv-gl** [comment]
@ruojianll @xiaowangsmile I have a pretty old working prototype here, please take it if you find it useful
[https://github.com/thuytv-gl/fabric-CJK-vertical]()
btw, @carior I fixed the stretching problem on recent commit

**Comment by new-sankaku** [comment]
Modifications have been made to the prototype.
-Added top, center, and bottom alignment functions.
-Rotated the characters a-zA-Z0-9 to write vertically (i.e. the same angle as normal horizontal writing).

Currently, the following issues remain.
-Text2VerticalText function doesn't work properly.
-Using "Line Height" multiple times causes the display to become distorted.
-"Character Spacing" has not been implemented at all.
-The font's Y and X axes do not scale when the top, bottom, left, or right corners of the box are grabbed.
-The font size does not scale when the top, bottom, bottom, left, or top left corners of the box are grabbed.
-Gradients do not work.

I think I'll be able to create something that works if I can fix the remaining issues.

Demo site：You can try it out in action on our Demo site.
https://new-sankaku.github.io/fabric-CJK-vertical/

![image](https://github.com/user-attachments/assets/8aa2c79e-5f3c-4d05-94d3-98e928b9c1c1)

**Comment by xiaowangsmile** [comment]
> Modifications have been made to the prototype. -Added top, center, and bottom alignment functions. -Rotated the characters a-zA-Z0-9 to write vertically (i.e. the same angle as normal horizontal writing).
> 
> Currently, the following issues remain. -Text2VerticalText function doesn't work properly. -Using "Line Height" multiple times causes the display to become distorted. -"Character Spacing" has not been implemented at all. -The font's Y and X axes do not scale when the top, bottom, left, or right corners of the box are grabbed. -The font size does not scale when the top, bottom, bottom, left, or top left corners of the box are grabbed. -Gradients do not work.
> 
> I think I'll be able to create something that works if I can fix the remaining issues.
> 
> Demo site：You can try it out in action on our Demo site. https://new-sankaku.github.io/fabric-CJK-vertical/
> 
> ![image](https://private-user-images.githubusercontent.com/133557155/375836725-8aa2c79e-5f3c-4d05-94d3-98e928b9c1c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2OTM4NjksIm5iZiI6MTcyODY5MzU2OSwicGF0aCI6Ii8xMzM1NTcxNTUvMzc1ODM2NzI1LThhYTJjNzllLTVmM2MtNGQwNS05NGQzLTk4ZTkyOGI5YzFjMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMlQwMDM5MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OTU4NzVmZjIyMmE5ZjY5YmRhMjhjOWM0ZGE5MjNiZjY0MjQ5Y2YxZGVjZTJlZjhiMTZiY2QyNDliZDYwMWI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ItQUubceSq5gBXormZHWW5L6uUgMwvVgPkz9JtECYO0)



This is really great. I hope you can solve these problems as soon as possible. Looking forward to your results

**Comment by asturur** [comment]
Vertical text would be nice to add but would require a full text rewrite in fabric imho.
I was planning that those days but is so much work i got scared and i started to do something else.

**Comment by xiaowangsmile** [comment]
Vertical text is very important for countries in East Asia, and we hope the author can restart the project as soon as possible. Thank you very much

**Comment by WuHaoX** [comment]
https://github.com/whatwg/html/issues/12034 I recently noticed that HTML natively plans to add support for vertical text in canvas. Have you considered adapting to this? Vertical text is very important for countries in East Asia。Thank you very much

**Comment by asturur** [comment]
If i had a backup that explains me the rules of vertical text i would definitely try.
Does at lest the textarea element support vertical text? That would be the minimum to understand what to expect.

**Comment by WuHaoX** [comment]
The writing mode in CSS can achieve excellent vertical text。 https://developer.mozilla.org/zh-CN/docs/Web/CSS/Reference/Properties/writing-mode

**Comment by asturur** [comment]
You underestimate the difficulty for me, not understanding how to read chinese script, to see if what i m rendering is correct or not.
How does the cursor is rendered to start with?

Chinese page:

<img width="794" height="386" alt="Image" src="https://github.com/user-attachments/assets/b19be048-004b-4275-9faa-9cc5942c90fd" />

English page with same setting:

<img width="773" height="386" alt="Image" src="https://github.com/user-attachments/assets/ec581afa-b24d-4774-a270-4c075d048a48" />

Is already confusing for me

Are gliph rotated? is that correct?

**Comment by WuHaoX** [comment]
https://www.w3.org/International/articles/vertical-text/#default_orientation This article aims to help you understand the rules of vertical text alignment. Regarding the cursor rules you mentioned, I used AI to generate a demo that effectively meets my text requirements. This demo is primarily implemented with CSS styles, involving properties like writing-mode, text-align, and direction. I hope it can also assist you in testing and understanding vertical text.

[test.html](https://github.com/user-attachments/files/24630934/test.html)

**Comment by J-env** [comment]
I also need officially supported vertical text. Thank you very much

```
import { Textbox } from 'fabric'

const text = new Textbox('竖版文字', {
vertical: true
})
```

**Comment by xiaowangsmile** [comment]
> https://www.w3.org/International/articles/vertical-text/#default_orientation This article aims to help you understand the rules of vertical text alignment. Regarding the cursor rules you mentioned, I used AI to generate a demo that effectively meets my text requirements. This demo is primarily implemented with CSS styles, involving properties like writing-mode, text-align, and direction. I hope it can also assist you in testing and understanding vertical text.
> 
> [test.html](https://github.com/user-attachments/files/24630934/test.html)

Vertical text is extremely important for East Asian countries. This demo is already very detailed, and if vertical text support could be added to Fabric.js, it would truly be a fantastic improvement.

**Comment by asturur** [comment]
i have in high regard supporting other people's cultures, so i would love to do that.
I can give it a stab when i m done with gradient controls

**Comment by WuHaoX** [comment]
I tried a rather clumsy solution, using ["html-to-image"](https://github.com/bubkoo/html-to-image) to convert HTML elements into SVG images and then add them to Fabric Canvas. The downside is that it cannot be edited, and loading custom fonts can be slower. This plan can temporarily help me solve some problems.
Thank you very much for the author's willingness to do this.

**Comment by xiaowangsmile** [comment]
> i have in high regard supporting other people's cultures, so i would love to do that. I can give it a stab when i m done with gradient controls

Hi, do you have any plans to work on this anytime soon?
