### ISSUE TITLE
svg output with clipPath inside <defs>

### ISSUE THREAD

**Issue by rikkarv** [fabricjs/fabric.js#5560]
**Is your feature request related to a problem? Please describe.**
TCPDF ignores clipPath outside "defs"

**Describe the solution you'd like**
Instead of getting "clipPath" tag outside the "defs" tag of the svg output (using .toSVG()) i would rather prefer to have it inside "defs".

**Additional context**
https://jsfiddle.net/wx68uy52/

**Comment by asturur** [comment]
adding clipPath to defs make them not influenced by group transforms.
While is still possible to do it, is an high effort.

I'm not even sure i nailed down the SVG clippath export yet.

**Comment by asturur** [comment]
Does it change something if you replace the clippath in the document with <use> tags and you move the clipPath in defs?

If that works you could postprocess the SVG to obtain the same

**Comment by rikkarv** [comment]
Thank you for your attention. I have already changed the svg string for testing and placed the clipPath tag inside defs tag. By doing that the TCPDF now recognize the clipPath. However now i am getting TCPDF wrong output because it renders the clipped image in a strange way. It seems to me this a TCPDF issue
________________________________

**Comment by asturur** [comment]
tcpdf is php?

pdf does not support svg specs at all.

I think the svg is handled as a forign object and so deferred to the pdf viewer rendering

This is what i learned time ago trying to make a pdf output for fabricjs.

If you have different knowledge please share

**Comment by asturur** [comment]
i'll close this issue since i have no action items.
We can't refactor how clipPath works to support TCPDF unless we find out we are violating some spec.
Feel free to investigate a bit and let me know if clipPah HAS TO be in the defs for the SVG to be valid.

**Comment by rikkarv** [comment]
Yes, tcpdf is indeed php. I'm not sure how it handles the svg but now i will have to dive a little deeper to find out. If i get more knowledge about it i will share with you later.
In the other hand i believe that it's not mandatory to have clipPath in defs because defs spec says that defs use is mostly for "understandability and accessibility" and only a recommendation.

**Comment by asturur** [comment]
with what are you viewing the resulting pdf? did you try changing reader to see if the clippaths are understood outside defs?

is tcpdf opensource? i have rusty php but i used and modified fpdf a lot.

**Comment by rikkarv** [comment]
Yes Andrea, tcpdf is opensource.
We use tcpdf in server side to allow the user of the application download a pdf file with the result of canvas.toSVG(), the pdf output it's not rendered in the app.
We have chosen tcpdf because it was one of the few libraries that didn't rasterize the svg.

**Comment by marcdakar** [comment]
tcpdf misplaced the clipped image in the pdf ... did you find a solution for this?

**Comment by rikkarv** [comment]
@marcdakar  we are still trying to solve this. Initially we changed the svg string output to include the clippath inside 'defs'. However there are issues with the transform attribute and we have to make some maths to fix this

**Comment by marcdakar** [comment]
@rikkarv i fixed it to the point that the clipped images looks good and right placed at 100%, but struggle with the problem that its not working when the clippath or the image is resized before svg-output

**Comment by asturur** [comment]
i think i can help a bit. do you have any tcpdf changes ore are you changing the svg itself?

**Comment by marcdakar** [comment]
@asturur ...the one thing i have to change in svg is the position of  <clipPath> into <defs>, otherwise tcpdf ignores it, ( it would be really nice if fabric could do this, perhaps with an optional parameter:
for example: canvas.toSVG({usedefs: {clipPath: true}} ) 
 ... the other issues are tcpdf specific, as rikkarv commented ... i have solved them yesterday ( a bit lousy) bei catch the transform attributes from clippath and groups and use them on the clipped image ... this works so far ... but i have to test ... 
did you have an another approach without changing tcpdf   ..   greetings

**Comment by asturur** [comment]
i think is better to pursue a fix in tcpdf.

The problem is not moving clippath into defs, is to give clippath the right transform. the current svg export code does not allow it correctly, and i still do not understand how it works exactly.

do you have a branch of tcpdf to look at?

**Comment by marcdakar** [comment]
@asturur  only the changed file, dont beat me for the quality of implemantation .... search for //karim
[tcpdf.zip](https://github.com/fabricjs/fabric.js/files/3026475/tcpdf.zip)

**Comment by asturur** [comment]
getting back to this just today, curios to see.

**Comment by marcdakar** [comment]
i have make a little progres in this but find no way if image inside clip is resized or rotated.

**Comment by asturur** [comment]
I have been busy since 20 april with hospitals and i did not look at anything.

**Comment by rikkarv** [comment]
Andrea i wish you that things get better soon
________________________________
