### ISSUE TITLE
Find canvas coordinates of text characters?

### ISSUE THREAD

**Issue by GreenFootballs** [fabricjs/fabric.js#6523]
Here's another weird question. I'm trying to think of a way to implement an editable "list" object, similar to an HTML &lt;ul> or &lt;ol> element, and I'd like to be able to position a bullet point (like a circle or square) at the start of each line of text in a TextBox object, offset from the left side of the TextBox by a certain amount. (By "line of text" I mean some text terminated with a linefeed.)

I see that the TextBox object has the property _unwrappedTextLines - if I could find the left/top position of each of the unwrapped line arrays that would do it.

Is there any way to get those coordinates from the object? 

Edit: investigating more I found the _lineHeights property, an array of heights for each line in the TextBox. This looks like it might work, except I'm not clear on how to distinguish a line that has wrapped vs. a line terminated with a linefeed.

**Comment by asturur** [comment]
The proper way to draw a list of items is to do a little ovverride and draw them during text rendering.
If you go back to canvas coordinates is going to be complicated.

https://github.com/fabricjs/fabric.js/blob/c43e1339aeee55f184d65f423fa4bf3553df484b/src/shapes/text.class.js#L527

Take _renderTextLine function, is just a passtrough to renderChars.

You can override just that function to add to the left var an offset, and later, render your bullet/numbering there.

Something like

```js
  _renderTextLine(method, ctx, line, left, top, lineIndex) {
      // get your bullet space, add it to left and render
      var myLeft = left + bulletSpace;
      this._renderChars(method, ctx, line, myLeft, top, lineIndex);
      // then render the bullet.
     var bullet = '😀' // find a char that looks like a bullet.
     this._renderChars(method, ctx, bullet, left, top, lineIndex);
  },
```

This is the easiest and most stable way to do it.

**Comment by GreenFootballs** [comment]
This looks like a much better idea! However, my first test isn't working - it's just drawing the text twice, not the bullet. [Here's a Codepen.](https://codepen.io/green_footballs/pen/bGppvyd?editors=0011)

**Comment by asturur** [comment]
Ok this is strange, i would have swear this is how i do it too.
I ll double check. But is definitely possible.

**Comment by GreenFootballs** [comment]
Could this be the issue?

https://github.com/fabricjs/fabric.js/blob/c43e1339aeee55f184d65f423fa4bf3553df484b/src/shapes/text.class.js#L905

This line in the _renderChars function seems to be ignoring the content passed to the function and getting the line of text directly out of the array.

**Comment by GreenFootballs** [comment]
That's it. If I set the textAlign to 'justify', it skips that code and renders the bullets.

[Here's the Codepen.](https://codepen.io/green_footballs/pen/bGppvyd?editors=0011)

However, it shows another problem -- the bullets are being added to every line, even if it's a wrapped line. Ideally, to allow the list to be edited easily, it should add bullets only to lines terminated with a linefeed.

**Comment by GreenFootballs** [comment]
Oops, and another issue - if the character spacing is set to non-zero, it applies that spacing to the Unicode code points and messes it up.

**Comment by asturur** [comment]
opening a pr to fix the shortcut code.

**Comment by asturur** [comment]
https://github.com/fabricjs/fabric.js/pull/6526/

**Comment by GreenFootballs** [comment]
Cool - that fixes the issue with the shortcut condition.

Do you have any thoughts on how to have the bullets appear only at the start of lines terminated with a linefeed, so it could behave a bit more like an HTML list?

Another problem with this approach is that the bounding rectangle no longer encloses the whole textbox. If you click on the object to select it, you'll see this. Is there a way to recalculate the bounding box to fit the bullets?

**Comment by asturur** [comment]
Yes i know. i implemented it at work, and wasn't extremely easy.
I'm not a fan of overrides nor of implementing too much stuff in the library.
I'll see what i can find for the new lines problem.

For the bounding box, not sure, more overrides :(

**Comment by GreenFootballs** [comment]
[Here's a way to handle the new lines issue and draw bullets only on full lines.](https://codepen.io/green_footballs/pen/bGppvyd)

But when I tried to edit the textbox by double-clicking, another issue came up: the editing code doesn't know about the offset for the bullets!

**Comment by GreenFootballs** [comment]
Found a solution for the bounding box issue. Instead of moving the text to the right, I draw the bullets at left - bulletWidth. So they're actually drawn outside the bounding box, and that seems to work fine. This fixes the issues with editing too, since the text is now where everything expects it to be. It's the same Codepen linked above if you want to look at it.

There's still an issue with drawing bullets in editing mode but I I think it's fixable. Is there a way to force the whole textbox object to be re-rendered?

**Comment by GreenFootballs** [comment]
If you have a minute could you please look at [the latest version](https://codepen.io/green_footballs/pen/bGppvyd?editors=0011) of this code, and notice what happens when you resize the textbox. There's some strange clipping behavior in the bullet areas I don't understand, but you'd probably know what's going on.

**Comment by GreenFootballs** [comment]
Figured it out! All I needed to do was turn off objectCaching for the textbox. This is now working great! Automatic list generation as you type.

**Comment by asturur** [comment]
i think you can leave objectCaching on ( is benificial mainly with text )
and add a bit of extra size to your cacheCanvas dimensions.

**Comment by GreenFootballs** [comment]
I'm still having an issue with this - the code is correctly rendering everything now, EXCEPT when I enter editing mode, select some text, and change any of the styles.

[Here's a Codepen demonstrating the issue.](https://codepen.io/green_footballs/pen/bGppvyd)

Changing the font size for a selection works correctly ONLY on the very first line of the pseudo-list. If you select text anywhere else in the textbox and change the size, the text size changes but the width of the selection area doesn't.

This example has both the pseudo-list and a normal Textbox object next to it, to show that changing a selection's font size works correctly in the normal Textbox. Do you have any idea what's going on here? It seems like it's missing a function call somewhere to regenerate the character widths.
