### ISSUE TITLE
Wrong combination of scaleY and top value in origin center mode in resize events

### ISSUE THREAD

**Issue by TFTomSun** [fabricjs/fabric.js#7153]
## Version
4.4.0

## Test Case
Issue with 4.4.0
http://jsfiddle.net/ue4w8a36/17/

I think its broken since 4.0.0. With 3.6.6 the issue isnt there:
http://jsfiddle.net/ue4w8a36/20/

## Information about environment
Nodejs or browser? browser 
Which browsers? chrome

## Steps to reproduce
- create reactangle with origin center
- bind scaling event
- try to calculate back the top border  of the rectangle based on the events target properties scaleY, top and strokeWidth and height. The assumption is that the following formula calculates the top border:
`args.target.top - args.target.scaleY * (args.target.height + args.target.strokeWidth) / 2.0`
 which worked in older fabricjs versions
- resize the rectangle quickly vertically

## Expected Behavior
The calculated top border value should always stays the same if the rectangle is resized vertically
## Actual Behavior
The calculated top border value differs from the actual value by +- 3 pixel ... on very fast resize operations it can even be more.

**Comment by i-prikot** [comment]
Hi. Why the calculated top border value should always stays the same? If the originX and originY set left and top?
http://fabricjs.com/test/misc/origin.html

Sorry if I don't understand something.

**Comment by TFTomSun** [comment]
Maybe I didn't explain the scenario well. As you can see in the fiddle, the rectangle is initialized with origin centerX/centerY. My goal is to calculate the top border y-coordinate of the rectangle. To do that I take the center point (which is left / top in the center origin case, and subtract the half of the actual height. The height can be calculated based on the initial height and the scaleY factor. However when I do this calculation I always end up with slightly different results when I just drag the bottom border down and up. Since the top border of the rectangle doesn't move when I just drag the bottom border, the calculation should always return the same value of the top border y-value. It works in version 3.3.6 but not in Version 4.

**Comment by i-prikot** [comment]
This can be affected by the `strokeUniform` parameter?

http://jsfiddle.net/i_prikot/zxk24qbv/ 4.4.0
http://jsfiddle.net/i_prikot/2n7dk8jv/ 3.6.6

**Comment by asturur** [comment]
hi @TFTomSun , the assumption of the formula is wrong or can be wrong, you shouldn't try to calculate it back.

If you want to know the top border you can do this.

object.getPointByOrigin('left', 'top') or getPointByOrigin('center', 'top').

The y coordinate of the resulting point is what you need.

The issue you see in 4.4.0 has been fixed in later 4.4.x versions anyway.
And was related to the fact that the control api at some point introduce a bug in which was firing the event with the previous scale value.

**Comment by asturur** [comment]
I will close the issue and reopen if this wasn't the solution

**Comment by TFTomSun** [comment]
The issue is still there in 4.5.0:
http://jsfiddle.net/ue4w8a36/17/

**Comment by asturur** [comment]
hi @TFTomSun i have seen you posted a comment about version 4.5.0
Was my comment useful in any way?

**Comment by TFTomSun** [comment]
Hi @asturur, yes it helped me. I wasn't aware that I didn't use the latest version. In 4.5.1 the calculation works as expected. The reason why I calculate the values, is because I am calling into fabricjs using blazor and try to reduce interop calls when possible in event handlers. But in case my use cases get more complicated, I'll fallback to the functions you mentioned. Thanks for your help.
